### ISSUE TITLE
floor() function to convert Float => Int

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/wdl4s#107]
We don't currently have a way of nicely converting a `Float` to an `Int`, one way to do this is to have some kind of `floor()` function.

**Comment by geoffjentry** [comment]
I think `floor`, `ceil` and `round` (or whatever) would be handy as standard functions. OTOH you'll get better luck if this is over in cromwell or wdl (IMO wdl)

**Comment by jsotobroad** [comment]
ahhh i put it in wdl first and thought it was wrong!  reopening ticket in wdl and closing this one -  https://github.com/broadinstitute/wdl/issues/110
