### ISSUE TITLE
Enable linting compiler options

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/wdl4s#130]
While upgrading Cromwell to 2.12 I was introduced to how much more thorough the various linting compiler flags were. I had to figure out how to disable some of the new behavior because some of the ills it was trying to prevent were far too ingrained in Cromwell's being to fix. 

That experience was eye opening and we should start being more aggressive with these compiler flags everywhere to prevent such a situation going forward

**Comment by mcovarr** [comment]
Do you feel this is covered by #135 or is this ticket asking for more?

**Comment by geoffjentry** [comment]
Yeah, 👍

**Comment by geoffjentry** [comment]
I was kinda hoping we could get the unused args one in here before we wind up in a Cromwellian situation but IIRC you mentioned it sucking over here too, so c'est la vie

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2707](https://github.com/broadinstitute/cromwell/issues/2707) via [**ZenHub**](https://www.zenhub.com/)
