### ISSUE TITLE
Web endpoints no longer returning pretty printed json

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/wdl4s#131]
I'm not sure why we were doing it in the first place but apparently in the Spray world we were actually pretty printing our JSON responses before sending it back to the client. 

I'm also not sure if this is behavior that we should continue with, but either way it's no longer the case with the akka http code. If it is behavior we want to maintain (I have a very weak preference towards "no"), this needs to be fixed.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2708](https://github.com/broadinstitute/cromwell/issues/2708) via [**ZenHub**](https://www.zenhub.com/)
