### ISSUE TITLE
Incorporate Schema Salad-ization before parsing CWL

### ISSUE THREAD

**Issue by danbills** [broadinstitute/wdl4s#141]
[Schema salad](https://github.com/common-workflow-language/schema_salad) is a preprocessor for CWL YAML.

 * It gives us a richer model w/ fully resolved references
 * It also would give us the JSON from YAML so we can remove the `circe-yaml` dependency.
 * Last but not least, we don't have to write the crazy map -> Array custom decoder because it's done as part of the pre-processing set

Background:
CWL uses references with special characters like `#` and `/`.

These should be de-referenced using [schema salad](https://github.com/common-workflow-language/schema_salad) together with the [Common Workflow Language schema](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/CommonWorkflowLanguage.yml).

This way the interpreter won't have to re-invent this wheel.

**Comment by danbills** [comment]
Suggesting a plan of attack:

 * declare a `SCHEMA_SALAD_PATH`
 * copy over the official CommonWorkflow schema into our repo
 * `./schema-salad-tool --quiet --print-pre /path/to/schema/CommonWorkflowLanguage.yml target_file`
 * parse the process output as Json
 * run all this with [Ammonite's lib for it](http://ammonite.io/#Ammonite-Ops)

**Comment by geoffjentry** [comment]
@danbills Thanks, I missed this earlier today :)

**Comment by danbills** [comment]
There is an example of using a pluggable service in:

 * Metadata service
 * "health service" as seen in cromwell `jg_status_endpoint` branch

The gist is that one can specify a fully qualified java class to be the implementation of a service.  Said class can be specified as a string in the config.

**Comment by danbills** [comment]
There's still work to use the actual tool as a pre-processor

**Comment by danbills** [comment]
use `cwltool --print-pre --quiet` instead of `schema-salad-tool`
