### ISSUE TITLE
Allow array-based parsing of Requirement

### ISSUE THREAD

**Issue by danbills** [broadinstitute/wdl4s#144]
Initially implemented a custom parser for Array[Requirement] [here](https://github.com/broadinstitute/wdl4s/blob/develop/cwl/src/main/scala/wdl4s/cwl/Implicits.scala#L49), but the behavior we want is to parse *either* arrays or maps.  

Essentially we need to `or` the map decoder with the "default" derived `Decoder[Array[Requirement]]`, but for some reason the auto derivation isn't working and need to figure out why.

**Comment by gemmalam** [comment]
https://github.com/broadinstitute/wdl4s/issues/141 was included in this issue.
