### ISSUE TITLE
Investigate long compile times for wdl4s cwl subproject

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/wdl4s#156]
It appears that some relatively recent changes have greatly extended compile times into multiple minutes, probably due to Circe decoding and encoding.  Investigate and see if there's anything that can be done to lessen the pain.

**Comment by geoffjentry** [comment]
@mcovarr "anything that can be done"

Remove Circe autoencoding? :)

On a serious note, wdl4s still needs to be bumped up to 2.12.3 which should help a bit. In fact I'll do that now.

**Comment by mcovarr** [comment]
We tried 2.12.3 locally and whatever improvement there was didn't rock our worlds.

**Comment by kshakir** [comment]
Some things to also try:

[![Generic Derivation: The Hard Parts—Travis Brown](http://img.youtube.com/vi/80h3hZidSeE/0.jpg)](https://youtu.be/80h3hZidSeE?t=34m7s "Generic Derivation: The Hard Parts—Travis Brown")

**Comment by danbills** [comment]
I propose we move everything JSON-related into a subproject that depends on the object model. 

This would allow rapid development and testing of CWL -> WOM.  

Json stuff is pretty small and contained so it wouldn't be too spaghetti-y.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2712](https://github.com/broadinstitute/cromwell/issues/2712) via [**ZenHub**](https://www.zenhub.com/)
