### ISSUE TITLE
Support CWL and WDL expressions in WOM

### ISSUE THREAD

**Issue by danbills** [broadinstitute/wdl4s#159]
There is no formal way to represent CWL expressions in WOM.

We seek to support the evaluation of both WDL and CWL expressions.

For reference: [CWL Expression](http://www.commonwl.org/v1.0/CommandLineTool.html#Expressions)

**Comment by danbills** [comment]
also see `outputEval` in [CommandLineBinding in CWL](http://www.commonwl.org/v1.0/Workflow.html#CommandOutputBinding)

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2732](https://github.com/broadinstitute/cromwell/issues/2732) via [**ZenHub**](https://www.zenhub.com/)
