### ISSUE TITLE
true & false statements in command

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/wdl4s#168]
The wdl docs say that when using the true/false syntax in the command block, one can get away with declaring just one of the 2, however the WDL fails validation and fails to create a namespace and therefore never gets run. 

AC:
Actually allow being able to declare True or False and statements OR Keep enforcing that both the behavior for true/false need to be defined, and adjust that expectation in the docs accordingly.

https://github.com/broadinstitute/wdl/blob/develop/SPEC.md#true-and-false

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2713](https://github.com/broadinstitute/cromwell/issues/2713) via [**ZenHub**](https://www.zenhub.com/)
