### ISSUE TITLE
Building wdl4s jar file

### ISSUE THREAD

**Issue by orodeh** [broadinstitute/wdl4s#176]
I have not found instructions for building a fat jar file for wdl4s. When `sbt-assembly` is used, you can do: 
```
sbt assembly
```
However, this is not the case for wdl4s. How does one build the fat jar file?

**Comment by geoffjentry** [comment]
Hi @orodeh - we don't build fat jars for `wdl4s`, we only do that for jars intended to be directly runnable by an end user.

You shouldn't need one though, what is it that you're trying to do? For instance if you have an sbt project you should just be able to pull it from artifactory and it'll grab what it needs.

**Comment by orodeh** [comment]
@geoffjentry, I am trying to modify the WDL grammar, so it will support optional attributes on task declarations. This would allow clean usage of DNAnexus extensions that are not directly part of the specification. For example, suggestions for an input ([DNAnexus applet spec](https://wiki.dnanexus.com/dxapp.json)), help strings, etc.

To do this, I am building wdl4s locally, and then using the fat jar file in [dxWDL](https://github.com/dnanexus-rnd/dxWDL). The wdl4s changes are in a forked branch, and it is not compiled to artifactory.

**Comment by orodeh** [comment]
In other words, the jar file I am missing is,  for version 0.13 of the library, `wdl4s_2.12-0.13.jar`. Is there a way to build it locally?

**Comment by geoffjentry** [comment]
Hi @orodeh - have you tried doing `sbt publishLocal`? That should put it in your local Ivy repository and get picked up by other builds.

**Comment by orodeh** [comment]
@geoffjentry, great, `sbt publishLocal` solves the problem nicely.
