### ISSUE TITLE
Enforce Witness types

### ISSUE THREAD

**Issue by danbills** [broadinstitute/wdl4s#184]
We have a couple classes in CWL (`Workflow` and `CommandLineTool`) that have awkward Witness types declared in the object.

Not only are they ugly, I'm pretty sure they don't work! 

The gotcha is that for some reason setting a default constructor arg didn't work and the compiler was saying that the argument isn't satisfactory despite the compiler accepting it as default.

The solution here is to *make the default constructor private* and write  constructor that fills in this value for the user.  Even if the bug were fixed this would be superior because one doesn't want to have to deal with a constructor arg that should only ever be one value.

**Comment by danbills** [comment]
By "don't work" I mean that one can supply any value and the parser will accept it.

**Comment by curoli** [comment]
They also don't work in the sense that occasionally, calls to constructor don't compile.

**Comment by curoli** [comment]
Why did this one get closed?

**Comment by gemmalam** [comment]
@curoli because the PR #214 was merged. Will there be another part to this ticket / should it be an epic @danbills?

**Comment by curoli** [comment]
Oh, right. Sorry, I got confused.

**Comment by danbills** [comment]
@gemlam3 there is no other part of this ticket and it is not an epic, so we're all set
