### ISSUE TITLE
findGlobPatterns in WomExpression

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/wdl4s#197]
Add a way to retrieve glob patterns contained in a WomExpression.

**Comment by danbills** [comment]
writing a note to myself that the general function here is 
`Glob -> IOFunctionSet -> IO[Set[WdlFile]]`

**Comment by danbills** [comment]
This is implemented for WomExpression and thus I am closing.  The spike ticket here has picked up the CWL aspect of it:
https://github.com/broadinstitute/cromwell/issues/2638
