### ISSUE TITLE
Make WomExpression evaluateValue method asynchronous

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/wdl4s#200]
This is a nice to have. `IoFunctionSet` already returns `Future`s for I/O methods. It would be nice to have the evaluate method itself be asynchronous to allow for a fully asynchronous evaluation.
Whether or not WDL evaluation should be made asynchronous too is left to implementor.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2729](https://github.com/broadinstitute/cromwell/issues/2729) via [**ZenHub**](https://www.zenhub.com/)
