### ISSUE TITLE
CWL Workflow name

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/wdl4s#202]
The CWL parser currently hardcode the same name for all workflows.
Find out if CWL has a way to specify a workflow name. If not use a hash ? A new endpoint parameter ?
@katevoss this could use PO input if it turns out CWL has no way to specify a workflow name

**Comment by danbills** [comment]
So it turns out that CWL v1.0.2 has an `id` field for Workflow, and cwltool gives us one for free:

http://www.commonwl.org/v1.0/Workflow.html#Workflow.

so we should update the model to have a required `id: String` and this problem goes away.

**Comment by danbills** [comment]
This also applies to `CommandLineTool`, cwltool pre-processing gives us one.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2728](https://github.com/broadinstitute/cromwell/issues/2728) via [**ZenHub**](https://www.zenhub.com/)
