### ISSUE TITLE
Custom WOM Call outputs

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/wdl4s#203]
Wom currently automatically derives call outputs from TaskDefinition.
CWL separately declares call outputs and "run" outputs, which mean the former could be a subset of the latter. Make it so that WOM can support this use case.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2727](https://github.com/broadinstitute/cromwell/issues/2727) via [**ZenHub**](https://www.zenhub.com/)
