### ISSUE TITLE
CWL Requirements, hints etc.. in WOM

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/wdl4s#204]
CWL has a lot of meta information that is currently not available in WOM.
This could be part of a larger work and include re-work of WDL runtime attributes but those bits need to make it to Cromwell somehow.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2726](https://github.com/broadinstitute/cromwell/issues/2726) via [**ZenHub**](https://www.zenhub.com/)
