### ISSUE TITLE
Add ability to export CWL to YAML

### ISSUE THREAD

**Issue by danbills** [broadinstitute/wdl4s#216]
We have existing tests (in ExportCwlSamplesSpec) that are testing output as previously implemented, yet library collisions forced us to remove that capability.

If and when [circe-yaml](https://github.com/circe/circe-yaml) updates their cats dependency we could use that.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2725](https://github.com/broadinstitute/cromwell/issues/2725) via [**ZenHub**](https://www.zenhub.com/)
