### ISSUE TITLE
Shenanigans with Prefix Separator

### ISSUE THREAD

**Issue by danbills** [broadinstitute/wdl4s#224]
Wom's Task Definition takes a prefix separator, but then callWithInputs takes its own separator!  Sort out these shenanigans and create one true prefix separator.

**Comment by mcovarr** [comment]
I was kind of hoping we could get rid of that prefix separator altogether once things are appropriately broken out into the language implementations.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2723](https://github.com/broadinstitute/cromwell/issues/2723) via [**ZenHub**](https://www.zenhub.com/)
