### ISSUE TITLE
Handle cwl.outputs.json with respect to outputBinding

### ISSUE THREAD

**Issue by danbills** [broadinstitute/wdl4s#237]
Per the CWL Spec:

>  If the file cwl.outputs.json is present in the output, outputBinding is ignored.

http://www.commonwl.org/v1.0/CommandLineTool.html#File

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2721](https://github.com/broadinstitute/cromwell/issues/2721) via [**ZenHub**](https://www.zenhub.com/)
