### ISSUE TITLE
Test CWL ECMAScript Functions

### ISSUE THREAD

**Issue by danbills** [broadinstitute/wdl4s#243]
Currently we are focused on delivering ECMAScript "Expressions" which are denoted w/ `$(...)`.

ECMAScript functions, denoted by `${....}` (i.e. w/ braces instead of parens) are as of yet untested.

Creating this ticket so I can move forward with spike https://github.com/broadinstitute/cromwell/issues/2638

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2719](https://github.com/broadinstitute/cromwell/issues/2719) via [**ZenHub**](https://www.zenhub.com/)
