### ISSUE TITLE
wdl4s returns declarations when we ask for inputs

### ISSUE THREAD

**Issue by helgridly** [broadinstitute/wdl4s#39]
We had a user who wrote a WDL that looks like this:

```
workflow pon_gatk_workflow {
    # Workflow input files
    File normal_bam_list
    Array[Array[String]] bam_file_names = read_tsv(normal_bam_list)
    String target_file
    File ref_fasta
    File ref_fasta_dict
    File ref_fasta_fai
    File gatk_jar
```

i.e. there's a declaration in the middle of their input block.

In Workbench we load this into wdl4s and call `Workflow.inputs`, which returns the list of inputs *and* the declaration, which is unexpected and very confusing to Rawls.

Looks like the issue is [right here](https://github.com/broadinstitute/wdl4s/blob/7f31fef89aecc26453c0459266a4e4e0adf4aee3/src/main/scala/wdl4s/Workflow.scala#L130).

**Comment by mcovarr** [comment]
Declarations can be uninitialized or initialized; uninitialized declarations should be returned by this method but I don't think initialized should be.

**Comment by mcovarr** [comment]
Oops I was wrong, this method is filtering out uninitialized declarations.  Looks like this is not a bug, though the documentation could be more clear.

**Comment by LeeTL1220** [comment]
@helgridly Are you sure that this is the WDL that should go into workbench?  Wouldn't it be easier to write a WDL that directly ingested ``Array[File]``?  The WDL is from gatk-protected.  I'd like to set up a convention using subworkflows.  It will play nicer with workbench's data model.  Come talk to me in person, if I am unclear.

**Comment by LeeTL1220** [comment]
@helgridly But I guess this version needs to be supported anyway....

**Comment by helgridly** [comment]
This WDL makes FC crash with a useless error. That's what I'm trying to
debug here. But it's not a wdl4s issue, hence thread closed.
