### ISSUE TITLE
method to return workflow with imports resolved, as a String

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/wdl4s#40]
The use case is described here:
https://gitter.im/broadinstitute/cromwell?at=580859f980020cc608f8996a 
and @cjllanwarne example describes exactly the kind of result we'd be after:
https://gist.github.com/cjllanwarne/31875cff989de8114751183ff09b202f
Thanks!

**Comment by ruchim** [comment]
@kcibul the ticket I was talking about.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2691](https://github.com/broadinstitute/cromwell/issues/2691) via [**ZenHub**](https://www.zenhub.com/)
