### ISSUE TITLE
A WDL less warnings would be nice

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/wdl4s#63]
Or maybe a lot less.  Currently 21 deprecation warnings compiling wdl4s with test code.  Seems more like a developer's choice task than a user request task or I'd look at this now:

```
...
[warn] /home/me/gitrepos/wdl4s/src/test/scala/wdl4s/types/WdlPairTypeSpec.scala:100: method load in object WdlNamespaceWithWorkflow is deprecated: To avoid unexpected default resolutions, I recommend using the load(String, Seq[ImportResolver] method of loading.
[warn]     noException should be thrownBy WdlNamespaceWithWorkflow.load(wdl)
[warn]                                                             ^
[warn] 21 warnings found
```

**Comment by knoblett** [comment]
If this is a part of the logging that happens after or while Cromwell is running, then this has been a frequent user request. The less (especially repeated) text printed to terminal the better, has been the general opinion of users I've interacted with.

**Comment by kshakir** [comment]
Nope, this is compile time only warnings. "Less logging" should be a different ticket filed in cromwell.

**Comment by katevoss** [comment]
Relating this to a similar log issue in [Cromwell #1884](https://github.com/broadinstitute/cromwell/issues/1883).

**Comment by mcovarr** [comment]
no longer an issue
