### ISSUE TITLE
cross-publish to ScalaJS

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/wdl4s#86]
If there will be ScalaJS support, then it will be possible to do things like validation of wdl4s directly in the browser

**Comment by geoffjentry** [comment]
that's an interesting point. My take is that I have nothing against doing it, for me personally it'd likely involve flipping the switch and if it Just Works great and if not (IIRC scala.js isn't 100% source compatible?) I'm not going to go much further. 

I mean this in a non-snarky way but this is really going to be in a "patches welcome" territory as I doubt it'll be officially prioritized and while I just added it to my "it'd be a good thing to do" mental todo list it's not the top item and I don't pop things off that list as frequently as I'd prefer.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2693](https://github.com/broadinstitute/cromwell/issues/2693) via [**ZenHub**](https://www.zenhub.com/)
