### ISSUE TITLE
wdl4s not erroring when a scatter variable is missing

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/wdl4s#92]
The following wdl currently parses in wdl4s without error, later causing an error within cromwell.

```
workflow undeclared_scatter_variable {
    scatter (i in undeclared) {}
}
```

See https://github.com/broadinstitute/cromwell/issues/2020 for more info of cromwell patches, including a centaur test, that may be updated or removed if this is fixed in wdl4s.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2699](https://github.com/broadinstitute/cromwell/issues/2699) via [**ZenHub**](https://www.zenhub.com/)
