### ISSUE TITLE
wdl4s not erroring when an output variable is missing

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/wdl4s#93]
The following wdl currently parses in wdl4s without error, later causing an error within cromwell.

```
task x {
    Int i
    command { echo $i }
    runtime { docker: "ubuntu" }
    output {
        Int out_but_intentionally_misnamed = i
        Boolean validOutput = i % 2 == 0
    }
}

workflow missing_optional_output {
  Array[Int] arr = [0,1,2,3]
  scatter (i in arr) {
    call x { input: i = i }
    if (x.validOutput) {
      Int x_out = x.out_except_undeclared
    }
  }

  Array[Int?] x_out_maybes = x_out
}
```

See https://github.com/broadinstitute/cromwell/issues/2020 for more info of cromwell patches, including a centaur test, that may be updated or removed if this is fixed in wdl4s.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2700](https://github.com/broadinstitute/cromwell/issues/2700) via [**ZenHub**](https://www.zenhub.com/)
